### ISSUE TITLE
Allow passing `className` prop

### ISSUE THREAD

**Issue by kruszczynski** [TwicPics/components#1]
Hello!

I'm a new user of TwicPics and I was excited to find that there's a React library I could use. 

However, my app uses [styled-components](https://styled-components.com/) for styling and that requires styled component to accept a `className` prop.

Do you think this is a good addition to the library?

I'm happy to take a stab at adding this around the end of the month - if that's something you're interested in.

**Comment by kruszczynski** [comment]
Awesome, I'll 👀 !

**Comment by jaubourg** [comment]
It's now fixed in 0.5.0 :)

**Comment by kruszczynski** [comment]
Awesome, I'll check it out later this week!
