### ISSUE TITLE
TwicImg or TwicPicture

### ISSUE THREAD

**Issue by Falcomfr** [TwicPics/components#102]
Hello,

What's the difference between TwicImg and TwicPicture ?
What do you mean by critical images?

Thanks you

**Comment by florentb** [comment]
`TwicImg` renders an `img` tag and uses Javascript to dynamically lazy-load a "pixel-perfect" image as the source (`src`).
`TwicPicture` renders a `picture` tag with several sources so the browser can choose the best one.

A "critical image" refers to an image that is deemed essential for the initial rendering of a webpage, particularly those that are visible above the fold.

We recommend using `TwicPicture` for critical images (especially if you use a framework that supports SRR) and `TwicImg` for off-screen media.

More info in this [article](https://www.twicpics.com/docs/guides/image-best-practices).

**Comment by mbgspcii** [comment]
@florentb was faster than i. But know you have my version too ;-)
