### ISSUE TITLE
Filter effect from preview stays active after real image is loaded

### ISSUE THREAD

**Issue by Kylyi** [TwicPics/components#11]
I'm using the Vue3 component to render my images.
While I love that it handles the `output=preview` for me, the filter effect stays active even after loading the "real" image.

I'd suggest either:
* `onLoad` event that triggers after the "real" image is rendered (so we can manually remove the background)
* adding a prop `keepPreview` (or some more suitable name :)) that handles automatic remove of the background

Or both :)

**Comment by Strift** [comment]
Hello @Kylyi, 

Thanks for opening a issue! 

The team has started thinking about this issue, although it can be prioritized right away. We'll get back to you as we have more progress on this.

Also, what is your use case for wanting to remove the background image (which is invisible anyway)?

Thanks,

**Comment by Kylyi** [comment]
Hi @Strift,

no worries, I've handled it on my side via component lifecycle events for now.

Anyway, my use-case is quite simple - I have an [image](https://gentl-logos.s3.eu-central-1.amazonaws.com/sp_product_page/person.webp) that has transparent background. When I load the imag via your custom component, the filter effect stays active which doesn't look good (IMO) in this scenario.

**Comment by mbgspcii** [comment]
Hi @Kylyi. 
Thank you for this anomaly. Very interesting case which should be corrected with the latest version of the components. Warning, this is a beta version: [0.9.0-beta.0](https://www.npmjs.com/package/@twicpics/components).

Hope it helps.

Best regards.
