### ISSUE TITLE
Please remove `console.log` on Vue3 component initialization

### ISSUE THREAD

**Issue by Kylyi** [TwicPics/components#12]
Could you please remove the comment that gets printed when initializing the component in Vue3?

As in:

![image](https://user-images.githubusercontent.com/19700450/174415336-4d4c5c2b-581f-4109-817b-fe67c3a664fa.png)

**Comment by mbgspcii** [comment]
Hi @Kylyi .
Thank you for the issue. 
This will be fixed in the next version.

Best regards.
