### ISSUE TITLE
Wrong documentation on ratio format

### ISSUE THREAD

**Issue by existe-deja** [TwicPics/components#17]
Hi,

I just noticed a misinformation inside the [ratio documentation](https://www.twicpics.com/fr/docs/api/manipulations#ratio). It indicates values should be separated by `:` but when I do this I get an error. Instead `/` works fine.

Thanks

**Comment by existe-deja** [comment]
Got it, I was applying url API params to components. URL only supports `:` and components `/`. It can lead to confusion.

**Comment by jaubourg** [comment]
We should probably support both `:` and `/` in the components `ratio` attribute. We used `:` in the URL API because `/` is the separator between transformations there.
