### ISSUE TITLE
[bug] Gatsby: Can't get placeholder to show

### ISSUE THREAD

**Issue by PeterDekkers** [TwicPics/components#20]
Using `"@twicpics/components": "^0.8.2"` and Gatsby I can't seem to configure a placeholder. I understand that it should be rendering as a background image, but none is present.

The warning `domain has not been configured` shows in the console (I believe it comes from [here](https://github.com/TwicPics/components/blob/ba34f63af37ece7a63c1f0bbc23ad83cee5768f3/src/_/placeholder.ts#L90:L92)), even though the domain has been configured in `gatsby-config.ts` and the main image _does_ load correctly using the `bar.twic.pics` domain.

```typescript
<TwicImg
    src="foo.jpg"
    ratio="2690/1793"
    placeholder="preview"
/>
```
... outputs...
```html
<div class="twic-i ">
    <div class="twic-w twic-tf" style="padding-top: 66.6667%;">
        <img alt="Foo" data-twic-src="image:foo.jpg" class=" twic-done" src="https://bar.twic.pics/foo.jpg?twic=v1/cover=2690x1793">. 
    </div>
</div>
```

I assume that this is a bug relating to the Gatsby integration.

**Comment by PeterDekkers** [comment]
If I add a call to `installTwicPics` in my page template, then it _does_ start working.

**Comment by mbgspcii** [comment]
Hi @PeterDekkers 

Thank you for opening an issue.

It is curious. It should work (see https://twicpics-gatsby-demo.netlify.app/twicPlaceholder ).

I have just created a small start-up project here https://github.com/mbgspcii/TwicPicsxGatsby-starter. Can you try to run it?

Eventually, can you give me the version of gatsby used and send me a copy of your configuration file?

**Comment by PeterDekkers** [comment]
Hello @mbgspcii. Thank you for setting up the project. It works perfectly, including placeholders. Feel free to close this issue. If I find out why the issue occurs in my codebase I will add an update here.

**Comment by PeterDekkers** [comment]
My Gatsby version is also `4.19.2`, just like your starter. The config also looked very similar to the starter config. My site is however an established website with many more moving parts.

**Comment by mbgspcii** [comment]
Hi @PeterDekkers.

Thank you for your feedback.

Glad it worked out.

I'm closing the issue but I'll keep an eye out for any news.

Best regards.

Miguel
