### ISSUE TITLE
[feature request] Load callback, or passing a ref to the image?

### ISSUE THREAD

**Issue by PeterDekkers** [TwicPics/components#21]
Currently, the only way to test if an image is loaded seem to be by looking at the CSS classes of the rendered components. In a React environment it would be nice to take advantage of the virtual DOM and e.g. pass a `ref` or load/error/progress callback functions to the image component.

My use case is a slide show, where I only want to advance to the next (responsive) image once it is loaded. I would like to avoid circumventing React and using `document.querySelector`.

**Comment by Strift** [comment]
Hello @PeterDekkers,

Good idea. Thanks for opening an issue. 
We have some team members on holiday right now, but we'll take a look at it asap (next week).

Cheers,

**Comment by jaubourg** [comment]
We need to properly design a means to check and/or react to the image being loading, loaded or in error. We'll probably need to use an observer that watches the img classname for this internally.
