### ISSUE TITLE
Variants for search engine bots

### ISSUE THREAD

**Issue by Strift** [TwicPics/components#22]
**Type:** Feature request

**Context**

Using the TwicPics script, it is possible to use the `data-twic-bot` attribute to apply transformations that are applied when Google and Bing crawling bots visit the site.

See feature documentation: https://www.twicpics.com/docs/script/attributes#data-twic-bot

**Objective**

Implement the same feature for TwicPics components

**Comment by mbgspcii** [comment]
Hi @Strift.

Version [0.9.0](https://www.npmjs.com/package/@twicpics/components/v/0.9.0) has just been released. 

It allows to specify SEO-friendly [TwicPics API transformations](https://www.twicpics.com/docs/api/transformations) for search engine bots through the `bot` attribute.

Transformations can be chained by entering a slash-separated list of [TwicPics API transformations](https://www.twicpics.com/docs/api/transformations).

An empty string (i.e `bot=""`) is also a possible value. In this case, there is no transformation applied to the media when search bots are visiting: it is the original media that is then referenced.

Yours.
