### ISSUE TITLE
[Nuxt 3] Rendered `<img>` in SSR (without JavaScript) not SEO friendly.

### ISSUE THREAD

**Issue by madebyfabian** [TwicPics/components#29]
Hi there,
first of all, very impressed on TwicPics! Easy onboarding, and within a few mins, I got everything set up.
I am planning to use it to optimize Supabase Storage Images.
I am using Nuxt 3, SSR.
When I am using the Nuxt Plugin like in the docs:

```vue
<template>
  <TwicImg src="path/name-of-my-image.jpg" />
</template>
```

This is what gets rendered by the server:
```html
<div class="twic-i">
   <div class="twic-w twic-tf" style="padding-top:;">
      <img alt="name-of-my-image" style="" data-twic-src="image:path/name-of-my-image.jpg">
      <div style=""></div>
   </div>
</div>
```
which is not SEO Friendly, since the img has no `src` param.

After the app mounts and the plugin ran, the markup looks fine, `<img>` now has a correct `src`.

Is there some guide on how to resolve this?

**Comment by madebyfabian** [comment]
Thanks for your answer @mbgspcii, I will take a look at the Article!

**Comment by mbgspcii** [comment]
Hi @madebyfabian 

I take the liberty of closing this issue and I add another [link to a small article](https://www.twicpics.com/blog/google-indexing-system-and-twicpics-components) that tries to answer your question. 

Do not hesitate to come back to us in case of other difficulties and thank you again for your question.

Yours sincerely.

Miguel.
