### ISSUE TITLE
[Nuxt 3 RC.9] Incompatibility issues

### ISSUE THREAD

**Issue by madebyfabian** [TwicPics/components#32]
I cannot get to run the latest `@twicpics/components/nuxt3` plugin at `^0.9.1` with the latest Nuxt 3 RC.9. This is probably due to a reason that is affecting other Nuxt Plugins too.

See:
- https://github.com/nuxt-modules/supabase/pull/73/files
- https://twitter.com/madebyfabian/status/1566930946099650561

```bash
 WARN  Module @twicpics/components is disabled due to incompatibility issues:
 - [nuxt] Nuxt version `^3.0.0` is required but currently using `3.0.0-rc.9`
```

I can offer to try fixing it and sending in a PR.

**Comment by mbgspcii** [comment]
Hi @madebyfabian.

Thank you for your suggestion but we have already solved this problem.

The fix will be released with the next version of components which will be deployed very very  soon (see [CHANGELOG](https://github.com/TwicPics/components/blob/dev/CHANGELOG.md#fixed)).

I will keep you informed as soon as the version is deployed.

Best regards.

**Comment by madebyfabian** [comment]
@mbgspcii Oh that's great to hear, thank you for the quick fixes! I'll close this issue then.

**Comment by mbgspcii** [comment]
@madebyfabian

The new version [0.10.0](https://www.npmjs.com/package/@twicpics/components/v/0.10.0) should fix the issue.

FYI, here is the [commit](https://github.com/TwicPics/components/commit/502c2498757a45b3c42d05dc390a8ee3a369b350) that handles the problem.

Thanks again. Keep us informed of the result.

I'm closing the issue in the hope that you won't need to reopen it. 🤞

M.
