### ISSUE TITLE
Svelte 3.52 with typescript has breaking changes with TwicPics

### ISSUE THREAD

**Issue by Korayem** [TwicPics/components#37]
npm package isn't up to date with latest Svelte changes
I followed the instructions in [official docs](https://www.twicpics.com/docs/components/svelte-3#questions-and-feedback) and got the following error:
```[{
	"resource": "/Users/***/Carousel.svelte",
	"owner": "_generated_diagnostic_collection_name_#4",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type 'SvelteComponentTyped<Attributes, undefined, undefined>' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.\n\nPossible causes:\n
- You use the instance type of a component where you should use the constructor type\n
- Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:\n  
- import type { SvelteComponentTyped } from \"svelte\";\n  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {}",
	"source": "ts",
	"startLineNumber": 14,
	"startColumn": 10,
	"endLineNumber": 14,
	"endColumn": 17
}]```

**Comment by mbgspcii** [comment]
Hi @Korayem.

Thank you for opening this issue.

Can you confirm that the error only appears in IDE and that your images are displayed or are you experiencing a problem during the build?

Obviously notice that we encounter this problem as soon as we use typescript and this whatever the version of svelte...

![image](https://user-images.githubusercontent.com/7620438/196889249-6aa8f0a3-594f-45ec-98de-fd424827a6a6.png)

**Comment by Korayem** [comment]
Thanks for your response @mbgspcii 

Indeed, I thought it might be a warning so I proceeded to run my sveltekit app but got this error:
<img width="869" alt="image" src="https://user-images.githubusercontent.com/198332/196945689-aaf6c58c-180c-4980-b197-4059a79f2fed.png">

This caused my page not to render...

I think Sveltekit is less forgiving than Svelte :)

**Comment by Korayem** [comment]
@mbgspcii  It may also be due to svelte embracing vite vs rollup in the past?

**Comment by mbgspcii** [comment]
HI @Korayem 

Using components with SvelteKit is a bit tricky: SvelteKit evolves very fast and there are still a lot of breaking changes.
At the moment, TwicPics components are not SSR compatible with SvelteKit.
If you don't need the ssr mode, you can add `export const ssr = false;`  in the `/routes/+layout.js` file

This file is not created by default. If it doesn't exist in your project, just add it with the single line `const ssr = false;`

Should normally work then.

Setting the TwicPics installation in layout.svelte will work as long as it is the base layout of the application (gg).

![image](https://user-images.githubusercontent.com/7620438/197041587-0390199e-9072-4976-af05-b6d63befa4f9.png)

![image](https://user-images.githubusercontent.com/7620438/197042145-95ea90fc-5342-41d0-b3a1-4e1be76436f3.png)

![image](https://user-images.githubusercontent.com/7620438/197042254-744dcb18-2ffc-4cb1-aa67-05e62ff045a8.png)

![image](https://user-images.githubusercontent.com/7620438/197042527-33d324cb-82f2-4304-b77c-49746b4eb20a.png)

Adapting TwicPics components to sveltekit's SRR mode is on our roadmap but not at the top of the list.

Tell us if the temporary deactivation of the ssr mode is problematic.

Hoping it helps.

Thank you for your feedback.

Regards.

Miguel

**Comment by Korayem** [comment]
Hey Miguel @mbgspcii 

Thanks again for the detailed response

I do need SSR in my project :)

Good news is, I managed to get Twicpic working in sveltekit. What I've done is extracted from the twipics project all the svelte specific code and added it manually to my project and it works like a charm. Needed a bit of tweaking here and there but it's working fine with SSR. 

This should do for now till you guys support Sveltekit. 
Here's what I copied 
* `src/_` > `lib/twicpic`
* `src/svelte3/*` > `components/*` (did some changes here to make it work)
<img width="208" alt="image" src="https://user-images.githubusercontent.com/198332/197147506-aba03b70-db4a-4503-9a43-27778cd62fef.png">


BTW is [Rich Harris announced RC in the last Svelte Summit](https://youtu.be/A8jkJTWacow?t=29653) (about a month ago) that SvelteKit won't have any breaking changes as they lock down Kit for 1.0.0 final release.

**Comment by mbgspcii** [comment]
Great++ @Korayem 

Thanks for the feedback and again bravo for adapting the TwicComponents to your SvelteKit project. 
We'll let you know as soon as we've adapted our components to SvelteKit.

Sincere greetings.

Miguel

**Comment by Korayem** [comment]
@mbgspcii I gave this another search to see what can be done to use the npm package with sveltekit without getting the error:
```<TwicPic is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules.```

I found this [documented way of loading](https://sapper.svelte.dev/docs/#Making_a_component_SSR_compatible) external packages client-side

So this is what I have now
`+layout.svelte`
```jsx
<script lang="ts">
  import { installTwicPics } from '@twicpics/components/svelte3';
  import '@twicpics/components/style.css';

  installTwicPics({
    // domain is mandatory
    domain: 'https://my-domain.twic.pics'
  });
</script>
```
A dummy wrapper for TwicImg (the same can be done for TwicVideo)
`components/TwicImg.svelte`
```jsx
<script lang="ts">
  import { onMount } from 'svelte';

  export let src;
  export let alt;
  export let classProp;

  //
  let TwicImg;

  onMount(async () => {
    const module = await import('@twicpics/components/svelte3');
    TwicImg = module.TwicImg;
  });
</script>

<svelte:component
  this={TwicImg}
  {src}
  {alt}
  class={classProp}
/>

```

Then in any page to use TwicImg
```jsx
<script lang="ts">
  import TwicImg from '$components/TwicImg.svelte';
</script>

<TwicImg alt="" classProp="" src="" />
```

Note I changed props `class` to `classProp` since `class` is reserved

The caveat with this approach is that SSR generates the page WITHOUT any <img> and all is done client-side which is slower and defeats the purpose of SSR

The 2nd approach people mentioned but couldn't figure out is to inform vite to precompile twicpics (requires installing the package as devDependency using `-D`). But I couldn't make this work...
`vite.config.js`
```js
  optimizeDeps: {
        include: [ '@twicpics/components/svelte3' ]
      },
```
Looking forward to having twicpics native sveltekit support

**Comment by mbgspcii** [comment]
Hi @Korayem 
I thank you for the time you spend to solve this problem. We have come to the same conclusion as you. 
We are looking for a solution that will allow the use of SSR. This task is scheduled in a near future.
We will keep you informed of our progress.
Sincerely yours.

Miguel

**Comment by angelokeirsebilck** [comment]
Any updates on this?

**Comment by raremiroir** [comment]
Am also facing this issue. Thanks @Korayem for your _at least temporary_ solution 🙏

**Comment by mbgspcii** [comment]
Hi.
We are currently modifying the generation of our Svelte3 components.
Once this step is done we will be able to expose TwicPics components usable with SvelteKit.
Sincerely yours.

Miguel

**Comment by mbgspcii** [comment]
Hi @Korayem, @angelokeirsebilck and @raremiroir.

We have just deployed version [0.15.0 ](https://www.npmjs.com/package/@twicpics/components/v/0.15.0) of our components. 

In this version we now support SvelteKit. This version also fixes Svelte Components typing.

Sorry for the delay and we hope you will be satisfied with this version.

Thanks again for using TwicPics and feel free to send us your feedback.

Sincerely yours.

Miguel

**Comment by Korayem** [comment]
Thank you @mbgspcii!

Will give it a whirl

**Comment by raremiroir** [comment]
Works like a charm, thanks @mbgspcii !
