### ISSUE TITLE
Supporting domain with path

### ISSUE THREAD

**Issue by YannDuv** [TwicPics/components#4]
I currently work on a Vue3 project that is deployed in three separated environments.
The way we handled those environments is by having a specific path to each other: `https://<our-domain>.twic.pics/<our-env-path>`
The problem is that when I try to feed the vue configuration with `app.use(TwicPics, { domain: 'https://<our-domain>.twic.pics/<our-env-path>'})`, I got this error:
```
Uncaught (in promise) Error: twicpics-components install domain "https://<our-domain>.twic.pics/<our-env-path>" is invalid
```

**Comment by mbgspcii** [comment]
Hello @YannDuv and thank you for using `TwicPics Components`.

Your use case is indeed not supported. 

In the current version, the configuration template expects for `domain` a value as configured on your `TwicPics` account. eg: 'https://<our-domain>.twic.pics.

That said, we find your idea of using paths at configuration time interesting.

The configuration of your requirement would become 

`app.use(TwicPics, { 
domain: 'https://<our-domain>.twic.pics',
path:'<our-env-path>'
})`


We are working on it right now.
