### ISSUE TITLE
Very slow load times

### ISSUE THREAD

**Issue by edwin323** [TwicPics/components#43]
Hi,
While testing TwicPics, we noticed that somes images can take up to 1.3sec to load due to waiting for server answer (see screenshot attached). 

We thought it was the first transfer time from our website to twicpics server, but after refreshing with disabled cache multiple times, on 10 trials we have around 50% of 30ms wait duration, and 50% of 1.2s wait. 

This if of course a dealbreaker for us, as currently on our CDN all assets take less than 50ms to load. Do you have an explanation?

![image](https://user-images.githubusercontent.com/36691858/205297488-aee24679-7516-4e94-a9a9-ca30d66d1d04.png)

**Comment by Strift** [comment]
Hello,

Thanks for opening an issue. Our team is investigating and will get back to you ASAP. 

Cheers,

**Comment by Strift** [comment]
Hi again,

It appears this issue is related to infrastructure and not the components code. Our team has reached out to you via the email associated with your TwicPics account.

Have a good day!
