### ISSUE TITLE
[Nuxt 3.0.0-rc.14] - ERROR  Cannot start nuxt:  Cannot set properties of undefined (setting 'twicpics') 

### ISSUE THREAD

**Issue by wilrelic** [TwicPics/components#45]
Getting this error with the module in Nuxt3 after upgrading to latest RC. I think it is referencing the config variable in nuxt.config.ts.

ERROR  Cannot start nuxt:  Cannot set properties of undefined (setting 'twicpics') 

Please advise.

**Comment by Strift** [comment]
Hi @wilrelic,

From the name of the issue, it appears that you are using Nuxt RC14. The latest stable version is Nuxt 3: https://github.com/nuxt/framework/releases/tag/v3.0.0

Cheers,

**Comment by mbgspcii** [comment]
Hi @wilrelic,

Do you still face the problem ?

Regards.

Miguel
