### ISSUE TITLE
Support crossorigin attribute

### ISSUE THREAD

**Issue by MasihTak** [TwicPics/components#56]
Adding a crossorigin attribute to image is a good pattern for having content security policy but unfortunately, it's not possible to set this attribute via the `TwicPics` component.

**Comment by mbgspcii** [comment]
Hi @MasihTak 

We have just released [0.31.0](https://www.npmjs.com/package/@twicpics/components/v/0.31.0) which should meet your needs.

Thanks for the issue and happy coding.
