### ISSUE TITLE
`<TwicImg>` component should not override empty strings in `alt` attributes

### ISSUE THREAD

**Issue by tomtuv** [TwicPics/components#74]
At the moment, the `<TwicImg>` React component replaces empty strings (even when deliberately added) with the image filename in `alt` attributes.

An empty `alt` attribute indicates to assistive technologies that the image is decorative and should be ignored. It is not the same as not having the attribute at all.

I've tried to add an ARIA role of `presentation` to the component which does the same thing as an empty `alt` attribute but it is not added to the `<img>` element. It would be useful if we could pass attributes to it as well.

Also, I think the default value when no `alt` attribute is specified should be empty strings instead of the image filename. This is what Next.js does for example with their `<Image>` component. It's better to hide the image for screen readers than to let them announce it with a potentially computer-generated filename.

For reference:

- https://www.w3.org/TR/WCAG20-TECHS/H67.html
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt
- https://nextjs.org/docs/pages/api-reference/components/image#alt

**Comment by tomtuv** [comment]
@mbgspcii Great news! Thanks for your quick response.

**Comment by mbgspcii** [comment]
Hi @tomtuv 

We have just deployed version [0.23.2](https://www.npmjs.com/package/@twicpics/components/v/0.23.2), which takes into account your request concerning the alt property.

In this version, the `alt` default value becomes an **empty string**.

We've also added to our roadmap the addition of the [ARIA role img ](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role) to our components.

Once again, we'll keep you informed.

Hoping [0.23.2](https://www.npmjs.com/package/@twicpics/components/v/0.23.2) will suit your current needs.

Regard.
