### ISSUE TITLE
TwicImg doesn't render inside Ionic <ion-item>

### ISSUE THREAD

**Issue by wstidolph** [TwicPics/components#8]
1. Create standard Ionic ([Ionic](https://ionicframework.com/)) /Angular application (Ionic v6, Angular v13)
2. Install TwicPics as per instructions (note: import TwicPicsComponentModule in the generated `src/app/home/home.module.ts`). Use TwicPics domain `'https://demo.twic.pics'`
3. You can set `  encapsulation: ViewEncapsulation.None` in the `home.page.ts` component, or not - this doesn't make a difference.
4. Modify `src/app/home/home.page.html` for a simple test:
````
<ion-content>
  <!-- when placed inside just an ion-content area, the TwicImg renders -->
  <TwicImg src="components/cat.jpg"></TwicImg>

  <!-- BUT when wrapped in <ion-item>
    the <TwicImg> component does not render; in fact
   it does not issue a network image request -->

  <ion-item>
    <TwicImg src="components/puppy.jpg"></TwicImg>
  </ion-item>
</ion-content>
````
5. `ionic serve` and open the browser ([localhost:8100/home](localhost:8100/home), by default) You see cat, but don't see puppy; dev tools shows no console messages, and there is no network request issued for the puppy.jpg

**Comment by wstidolph** [comment]
NOTE: workaround to stay inside the `ion-item` is to install TwicPics as before (that seems to get the script installed) but use an <img> tag rather than TwicImg, e.g.,
```
  <ion-item>
      <img  data-twic-src="image:components/puppy.jpg?twic=v1/crop=400x300@350x300">
  </ion-item>
```

**Comment by mbgspcii** [comment]
Hi @wstidolph and thanks for using TwicPics Components.

I confirm to reproduce your problem.
I have created a small repo for this purpose: 
`git clone https://github.com/mbgspcii/my-first-angular-ionic-app.git`
`cd my-first-angular-ionic-app/`
`npm install && npm ionic serve`

As you can see, in the "Ion Grid" page the component integration works correctly.

In the "Ion Item" page, the first item reproduces your case.
The other cases on this page seem to work adequately.

What is happening there?

TwicPics components adapt in width to the size of their containers.
Their height is then calculated according to this width and any value passed as `ratio` property (1 by default).

In the cases that work on this page, we have : 
- either added a container with a specified width to the TwicImg component ("ion-item + ion-thumbnail as container", "ion-item + custom div as container", "ion-item + div as container + TwicImg focus and ratio")
- or specified the width of the TwicPics Component ("Twic image right under the Ion Item but with specified width").

However, it seems that a width:100% is missing for the `twicimg` element that persists in dom (in angular version) and that this forces the user to set the width of the container in your case: we will look at this problem more closely.

Kind regards.

**Comment by wstidolph** [comment]
Ah, I kind of knew it was a 'width' issue, but I didn't think to just set the width as easily as you did, with `ion-thumbnail` or `class="sm"` - much nicer than my workaround (for being able to use CSS selectors) - thanks!

**Comment by wstidolph** [comment]
BTW, the same thing happens with using TwicImg to supply the image for Swiper.js swiperSlides ... if I don't set the width of the `TwicImg` then it chooses a size of 0x0, but setting the `width` directly on the `TwicImg` will get the image rendered (and sized to the enclosing `div.swiper-slide`:
```
 <swiper #swiper [config]="config">
    <ng-template swiperSlide
      *ngFor="let pd of pdArray; let i=index ">
        <TwicImg style="width:100%"
          [src]="pd?.img_basename"
        ></TwicImg>
    </ng-template>
  </swiper>
```
(`pdArray` is just the objects I'm handling, each with a `img_basename` property)

**Comment by wstidolph** [comment]
Oops - sorry ... you should be skeptical of my claim that wrapping the `TwicImg` in an `<a>` is what caused the width to go back to 0; it looks to me like I had mixed in the swiper styles and  the `::ng-deep` styles from the TwicImg demo.

Here's what I'm doing in which the `<a>`-wrapped `TwicImg` is rendering nicely, without hard-coding the `width` in the template at all:

From the template:
```
 <swiper #swiper [config]="config">

    <ng-template swiperSlide class="twic-life-cycle"
      *ngFor="let pd of pdArray; let i=index ">
      <a
        [routerLink]="['/pic', pd?.img_basename]" routerDirection="forward">

          <TwicImg
            [src]="pd?.img_basename"
            [focus]="pd?.twicFocus"
            transition="fade+zoom"
            ratio="4/3"
            mode="cover"
          ></TwicImg>

      </a>

      <ion-label >({{i}}) {{pd.img_basename}}</ion-label>
    </ng-template>
  </swiper>
```
From the page's .scss:
```
.display-block-pointer {
  cursor: pointer;
  display: block;
  width: 100%;
  height: 100%;
}

.twic-life-cycle {
  twicimg {
      @extend .display-block-pointer;

      & ::ng-deep img {
          @extend .display-block-pointer;
      }
  }
}

// swiper styling from swiper demo
// https://codesandbox.io/s/fw3wws?file=/src/app/app.components.scss
.swiper {
  width: 100%;
  height: 100%;
  margin-left: auto;
  margin-right: auto;
}

.swiper-slide {
  text-align: center;
  font-size: 18px;
  background: #fff;
  // still need to reduce height for non-overlap with the ion-label
  // or maybe split the slide into two parts using grid
  // this calc shouldn't depend on the hardcoded divisor, it should adapt
  // to screen size and number of rows
  height: calc((100% - 30px) /4) !important;
}
```

From the component:
```
config: SwiperOptions = {

    slidesPerView: 2,
    grid: {
       rows: 3,
    },
    spaceBetween: 20,
    pagination: {
      clickable: true,
      renderBullet: function (index, className) {
        return '<span class="' + className + '">' + (index + 1) + "</span>";
      }
    }
  }

```
I'm kind of hacking around here, I'm not good with CSS (yet!) ... it would be nice to see an expert's demo on putting TwicImg properly inside a swiper.js grid :)

**Comment by mbgspcii** [comment]
Hi @wstidolph.
Version `0.8.1` of the TwicPics Components should fix the problem initially reported (width issue).

I take note of your question about the implementation in swipe.js.
I will come back to you soon with an example.

Thank you for the issue.

Best regards.
