### ISSUE TITLE
<TwicImg /> default ratio of 1

### ISSUE THREAD

**Issue by chrispcode** [TwicPics/components#83]
Why is the default ratio 1, shouldn't it be the ratio of the image i am requesting?

**Comment by chrispcode** [comment]
Also is it possible to just give us a simple height or width property?

**Comment by mbgspcii** [comment]
Hi @chrispcode 

Thank you for your questions.

The default `ratio` avoids `CLS` as we don't know the intrinsic dimensions of the image _a priori_.

If you know the image's intrinsic dimensions when you create your template, you can set the ratio property to (intrinsic width) / (intrinsic height). For example `ratio = 2080/1386`

TwicPics components don't expose `width` and `height` properties: they adapt to the dimensions of their container.

That said, you can use `ratio="none"` and regain total control of the display:
- by imposing dimensions on TwicPics components
- by imposing dimensions on the container of TwicPics components

Here's a [little example in react](https://stackblitz.com/edit/vitejs-vite-zymxme?file=src%2FApp.css,src%2FApp.jsx,src%2Findex.css&terminal=dev) that might help.

If you'd like to find out more about the layout driven pattern adopted by TwicPics components, here's [a link to an article describing in greater depth how it works](https://www.twicpics.com/blog/how-to-automate-reponsive-image-resizing-with-nextJS-and-twicpics).

Please note that using `ratio="none" `means **you must define a height** for your image (or video) (see the examples in the [short demo](https://stackblitz.com/edit/vitejs-vite-zymxme?file=src%2FApp.css,src%2FApp.jsx,src%2Findex.css&terminal=dev)).


Hoping it helps.
