### ISSUE TITLE
TwicImg for react-native doesn't seem to get cached

### ISSUE THREAD

**Issue by jamiechong** [TwicPics/components#84]
My Expo based React Native app doesn't seem to want to cache the images. Every time I load the exact same image, the network tab in inspector is showing a network request for the same image.

I will note that even the Image imported from react-native behaves this way. But if I use [Expo Image](https://docs.expo.dev/versions/latest/sdk/image/), caching works as expected.

Any thoughts on why caching is not working?

**Comment by mbgspcii** [comment]
Hi @jamiechong 

You're right. We don't manage caches.
We are adding this request for a feasibility study and will get back to you with an update.

Thank you for this issue.

**Comment by mbgspcii** [comment]
Hi @jamiechong 

If you're still interested, we've just released version 0.29.0, which manages image caching.
Activating the cache requires you to add expo-image to your project's list of dependencies.

Here's a [demo github repo](https://github.com/TwicPics/components-demo-react-native).

Please note the modification made to the component setup [here](https://github.com/TwicPics/components-demo-react-native/blob/main/App.js#L23).

If you have any problems or questions, please do not hesitate to contact us.

Happy coding.
