### ISSUE TITLE
TwicImg React - Can't set draggable to false

### ISSUE THREAD

**Issue by motiazu** [TwicPics/components#87]
I'm working on a UI with draggable interactions, TwicImg does not let me pass `draggable={false}`.
This means that on desktop the images get dragged instead of the elements that contain them, as I intended.
For the time being this means I can't use `TwicImg` for these images and having to use `<img />` directly instead.

Would love to see it added, and ideally any existing `img` attribute.

**Comment by mbgspcii** [comment]
HI @motiazu .

This should me fixed with [0.31.0](https://www.npmjs.com/package/@twicpics/components/v/0.31.0)

Sorry for the delay.

Happy coding.
